import type { TemplateCategory, InviteTemplate, TemplateFieldConfig } from "@/types/template";
import type { Invite, RSVPEntry } from "@/types/invite";

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const mockCategories: TemplateCategory[] = [
  { id: "birthday",   name: "Төрсөн өдөр",          slug: "birthday",   icon: "🎂", order: 1 },
  { id: "wedding",    name: "Хуримын ёслол",         slug: "wedding",    icon: "💍", order: 2 },
  { id: "graduation", name: "Төгсөлтийн ёслол",      slug: "graduation", icon: "🎓", order: 3 },
  { id: "corporate",  name: "Корпорейт арга хэмжээ", slug: "corporate",  icon: "🏢", order: 4 },
  { id: "kids",       name: "Хүүхдийн баяр",         slug: "kids",       icon: "🎈", order: 5 },
  { id: "other",      name: "Бусад арга хэмжээ",     slug: "other",      icon: "🎉", order: 6 },
];

// ---------------------------------------------------------------------------
// Shared field builders
// ---------------------------------------------------------------------------

function titleField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-event-title",
    key: "event_title",
    label: "Арга хэмжээний нэр",
    placeholder: "Жишээ: Анужин 6 нас",
    type: "text",
    required: true,
    x: 80, y: 480, width: 920, height: 110,
    fontFamily: "Montserrat",
    fontSize: 64,
    fontWeight: 700,
    lineHeight: 1.2,
    maxChars: 60,
    color: "#1a1a2e",
    align: "center",
    visible: true,
    locked: false,
    layerOrder: 2,
    ...overrides,
  };
}

function hostNameField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-host-name",
    key: "host_name",
    label: "Зохион байгуулагчийн нэр",
    placeholder: "Жишээ: Дулмаа",
    type: "text",
    required: true,
    x: 80, y: 620, width: 920, height: 80,
    fontFamily: "Montserrat",
    fontSize: 40,
    fontWeight: 400,
    lineHeight: 1.3,
    maxChars: 80,
    color: "#444466",
    align: "center",
    visible: true,
    locked: false,
    layerOrder: 3,
    ...overrides,
  };
}

function eventDateField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-event-date",
    key: "event_date",
    label: "Огноо",
    placeholder: "2026-07-20",
    type: "date",
    required: true,
    x: 80, y: 780, width: 440, height: 64,
    fontSize: 36,
    fontWeight: 500,
    color: "#222244",
    align: "center",
    visible: true,
    locked: false,
    layerOrder: 4,
    ...overrides,
  };
}

function eventTimeField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-event-time",
    key: "event_time",
    label: "Цаг",
    placeholder: "14:00",
    type: "time",
    required: true,
    x: 560, y: 780, width: 440, height: 64,
    fontSize: 36,
    fontWeight: 500,
    color: "#222244",
    align: "center",
    visible: true,
    locked: false,
    layerOrder: 5,
    ...overrides,
  };
}

function locationField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-location",
    key: "location",
    label: "Байршил",
    placeholder: "Жишээ: Шангри-Ла зочид буудал",
    type: "location",
    required: false,
    x: 80, y: 900, width: 920, height: 80,
    fontSize: 32,
    fontWeight: 400,
    color: "#555577",
    align: "center",
    visible: true,
    locked: false,
    layerOrder: 6,
    ...overrides,
  };
}

function rsvpButtonField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-rsvp",
    key: "rsvp_button",
    label: "RSVP товч",
    type: "rsvp",
    required: false,
    x: 240, y: 1720, width: 600, height: 96,
    fontSize: 36,
    fontWeight: 600,
    color: "#ffffff",
    align: "center",
    borderRadius: 48,
    visible: true,
    locked: false,
    layerOrder: 10,
    ...overrides,
  };
}

function coverImageField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-cover-image",
    key: "cover_image",
    label: "Зураг",
    type: "image",
    required: false,
    x: 0, y: 120, width: 1080, height: 300,
    objectFit: "cover",
    borderRadius: 0,
    visible: true,
    locked: false,
    layerOrder: 1,
    ...overrides,
  };
}

function qrField(overrides?: Partial<TemplateFieldConfig>): TemplateFieldConfig {
  return {
    id: "f-qr",
    key: "qr_code",
    label: "QR код",
    type: "qr",
    required: false,
    x: 440, y: 1560, width: 200, height: 200,
    visible: true,
    locked: true,
    layerOrder: 9,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

export const mockTemplates: InviteTemplate[] = [
  // 1. birthday-pastel
  {
    id: "tpl-001",
    name: "Пастел төрсөн өдөр",
    slug: "birthday-pastel",
    categoryId: "birthday",
    type: "image",
    backgroundUrl: "/mock-templates/birthday-pastel.svg",
    thumbnailUrl: "/mock-templates/birthday-pastel.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      coverImageField({ id: "f-001-cover", y: 100, height: 360, borderRadius: 24 }),
      titleField({
        id: "f-001-title",
        y: 520,
        color: "#c2185b",
        fontSize: 72,
        fontFamily: "Nunito",
        placeholder: "Анужин 6 нас",
      }),
      hostNameField({
        id: "f-001-host",
        y: 660,
        color: "#880e4f",
        fontSize: 38,
        placeholder: "Дулмаагийн Анужин",
      }),
      eventDateField({ id: "f-001-date", y: 800, color: "#ad1457" }),
      eventTimeField({ id: "f-001-time", y: 800, color: "#ad1457" }),
      locationField({
        id: "f-001-loc",
        y: 920,
        color: "#6d4c7d",
        placeholder: "Улаанбаатар хот, Сүхбаатар дүүрэг",
      }),
      {
        id: "f-001-note",
        key: "note",
        label: "Нэмэлт мэдээлэл",
        placeholder: "Ирэхдээ бэлэг авчрахаа мартуузай!",
        type: "text",
        required: false,
        x: 80, y: 1060, width: 920, height: 120,
        fontSize: 28,
        fontWeight: 400,
        color: "#9c4488",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 7,
      },
      rsvpButtonField({ id: "f-001-rsvp", color: "#ffffff" }),
    ],
  },

  // 2. wedding-classic
  {
    id: "tpl-002",
    name: "Сонгодог хурим",
    slug: "wedding-classic",
    categoryId: "wedding",
    type: "image",
    backgroundUrl: "/mock-templates/wedding-classic.svg",
    thumbnailUrl: "/mock-templates/wedding-classic.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      coverImageField({ id: "f-002-cover", y: 80, height: 400, objectFit: "cover" }),
      {
        id: "f-002-couple",
        key: "couple_names",
        label: "Хосын нэр",
        placeholder: "Бат-Эрдэнэ & Солонго",
        type: "text",
        required: true,
        x: 80, y: 540, width: 920, height: 120,
        fontFamily: "Playfair Display",
        fontSize: 68,
        fontWeight: 700,
        lineHeight: 1.25,
        maxChars: 50,
        color: "#2c1810",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 2,
      },
      titleField({
        id: "f-002-title",
        y: 700,
        color: "#5d4037",
        fontSize: 40,
        fontWeight: 400,
        placeholder: "Хуримын ёслолд урьж байна",
      }),
      hostNameField({
        id: "f-002-host",
        y: 790,
        color: "#795548",
        fontSize: 34,
        placeholder: "Зохион байгуулагч: Батын Болормаа",
      }),
      eventDateField({ id: "f-002-date", y: 920, color: "#4e342e" }),
      eventTimeField({ id: "f-002-time", y: 920, color: "#4e342e" }),
      locationField({
        id: "f-002-loc",
        y: 1040,
        color: "#6d4c41",
        placeholder: "Шангри-Ла зочид буудал, Улаанбаатар",
      }),
      qrField({ id: "f-002-qr" }),
      rsvpButtonField({ id: "f-002-rsvp" }),
    ],
  },

  // 3. wedding-luxury
  {
    id: "tpl-003",
    name: "Тансаг хурим",
    slug: "wedding-luxury",
    categoryId: "wedding",
    type: "image",
    backgroundUrl: "/mock-templates/wedding-luxury.svg",
    thumbnailUrl: "/mock-templates/wedding-luxury.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      coverImageField({ id: "f-003-cover", y: 0, height: 480, borderRadius: 0 }),
      {
        id: "f-003-couple",
        key: "couple_names",
        label: "Хосын нэр",
        placeholder: "Энхбаяр & Номин",
        type: "text",
        required: true,
        x: 80, y: 540, width: 920, height: 130,
        fontFamily: "Cormorant Garamond",
        fontSize: 76,
        fontWeight: 700,
        lineHeight: 1.2,
        maxChars: 50,
        color: "#b8960c",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 2,
      },
      {
        id: "f-003-tagline",
        key: "tagline",
        label: "Уриа үг",
        placeholder: "Хамт мөнхийн аялалд гарна",
        type: "text",
        required: false,
        x: 120, y: 700, width: 840, height: 72,
        fontFamily: "Cormorant Garamond",
        fontSize: 36,
        fontWeight: 400,
        color: "#c9a84c",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 3,
      },
      eventDateField({ id: "f-003-date", y: 840, color: "#8d6e00", fontSize: 40 }),
      eventTimeField({ id: "f-003-time", y: 840, color: "#8d6e00", fontSize: 40 }),
      locationField({
        id: "f-003-loc",
        y: 960,
        color: "#7a6020",
        placeholder: "Шангри-Ла зочид буудал, Улаанбаатар",
      }),
      hostNameField({
        id: "f-003-host",
        y: 1080,
        color: "#9e7c14",
        placeholder: "Зохион байгуулагч: Лувсандорж гэр бүл",
      }),
      qrField({ id: "f-003-qr", x: 420, y: 1540 }),
      rsvpButtonField({ id: "f-003-rsvp", y: 1720, color: "#1a1208" }),
    ],
  },

  // 4. birthday-kids
  {
    id: "tpl-004",
    name: "Хүүхдийн баяр",
    slug: "birthday-kids",
    categoryId: "kids",
    type: "image",
    backgroundUrl: "/mock-templates/birthday-kids.svg",
    thumbnailUrl: "/mock-templates/birthday-kids.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      coverImageField({ id: "f-004-cover", y: 80, height: 340, borderRadius: 32 }),
      titleField({
        id: "f-004-title",
        y: 480,
        color: "#e91e63",
        fontSize: 80,
        fontFamily: "Nunito",
        fontWeight: 800,
        placeholder: "Бат-Өлзий 5 нас",
      }),
      {
        id: "f-004-subtitle",
        key: "subtitle",
        label: "Дэд гарчиг",
        placeholder: "Баяртай баярт тавтай морил!",
        type: "text",
        required: false,
        x: 80, y: 610, width: 920, height: 72,
        fontFamily: "Nunito",
        fontSize: 38,
        fontWeight: 600,
        color: "#9c27b0",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 3,
      },
      hostNameField({ id: "f-004-host", y: 720, color: "#7b1fa2", placeholder: "Мөнхөөгийн Бат-Өлзий" }),
      eventDateField({ id: "f-004-date", y: 840, color: "#1565c0" }),
      eventTimeField({ id: "f-004-time", y: 840, color: "#1565c0" }),
      locationField({
        id: "f-004-loc",
        y: 960,
        color: "#0277bd",
        placeholder: "Хүүхдийн цэцэрлэгт хүрээлэн, Хан-Уул дүүрэг",
      }),
      rsvpButtonField({ id: "f-004-rsvp", y: 1720 }),
    ],
  },

  // 5. graduation-modern
  {
    id: "tpl-005",
    name: "Орчин үеийн төгсөлт",
    slug: "graduation-modern",
    categoryId: "graduation",
    type: "image",
    backgroundUrl: "/mock-templates/graduation-modern.svg",
    thumbnailUrl: "/mock-templates/graduation-modern.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      coverImageField({ id: "f-005-cover", y: 60, height: 360, borderRadius: 16 }),
      titleField({
        id: "f-005-title",
        y: 480,
        color: "#1a237e",
        fontSize: 62,
        fontFamily: "Montserrat",
        fontWeight: 700,
        placeholder: "Төгсөлтийн ёслол 2026",
      }),
      {
        id: "f-005-degree",
        key: "degree",
        label: "Мэргэжил / Зэрэг",
        placeholder: "Програм хангамж инженерч",
        type: "text",
        required: false,
        x: 80, y: 620, width: 920, height: 72,
        fontSize: 36,
        fontWeight: 500,
        color: "#283593",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 3,
      },
      hostNameField({
        id: "f-005-host",
        y: 730,
        color: "#3949ab",
        placeholder: "Гантулгын Цэнгэл",
        fontSize: 36,
      }),
      eventDateField({ id: "f-005-date", y: 860, color: "#1a237e" }),
      eventTimeField({ id: "f-005-time", y: 860, color: "#1a237e" }),
      locationField({
        id: "f-005-loc",
        y: 980,
        color: "#3f51b5",
        placeholder: "МУИС-ийн их танхим, Сүхбаатар дүүрэг",
      }),
      qrField({ id: "f-005-qr", x: 420, y: 1540 }),
      rsvpButtonField({ id: "f-005-rsvp" }),
    ],
  },

  // 6. corporate-elegant
  {
    id: "tpl-006",
    name: "Корпорейт урилга",
    slug: "corporate-elegant",
    categoryId: "corporate",
    type: "image",
    backgroundUrl: "/mock-templates/corporate-elegant.svg",
    thumbnailUrl: "/mock-templates/corporate-elegant.svg",
    canvasWidth: 1080,
    canvasHeight: 1920,
    status: "published",
    fields: [
      {
        id: "f-006-logo",
        key: "company_logo",
        label: "Компанийн лого",
        type: "image",
        required: false,
        x: 390, y: 100, width: 300, height: 160,
        objectFit: "contain",
        visible: true,
        locked: false,
        layerOrder: 1,
      },
      titleField({
        id: "f-006-title",
        y: 320,
        color: "#0d1b2a",
        fontSize: 58,
        fontFamily: "Montserrat",
        fontWeight: 700,
        placeholder: "Жилийн тайлант хурал 2026",
        height: 130,
      }),
      {
        id: "f-006-org",
        key: "organization",
        label: "Байгууллагын нэр",
        placeholder: "Монгол Телеком ХК",
        type: "text",
        required: true,
        x: 80, y: 490, width: 920, height: 72,
        fontSize: 38,
        fontWeight: 600,
        color: "#1b3a5c",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 3,
      },
      hostNameField({
        id: "f-006-host",
        y: 600,
        color: "#2c5282",
        placeholder: "Гүйцэтгэх захирал: Д. Мөнхбаяр",
        fontSize: 34,
      }),
      eventDateField({ id: "f-006-date", y: 740, color: "#1a3c5e" }),
      eventTimeField({ id: "f-006-time", y: 740, color: "#1a3c5e" }),
      locationField({
        id: "f-006-loc",
        y: 860,
        color: "#2a4a6b",
        placeholder: "Кемпински зочид буудал, Хан-Уул дүүрэг",
      }),
      {
        id: "f-006-dresscode",
        key: "dress_code",
        label: "Хувцасны дресс-код",
        placeholder: "Ёслолын хувцас",
        type: "custom",
        required: false,
        x: 80, y: 1000, width: 920, height: 60,
        fontSize: 30,
        fontWeight: 400,
        color: "#4a6080",
        align: "center",
        visible: true,
        locked: false,
        layerOrder: 7,
      },
      qrField({ id: "f-006-qr" }),
      rsvpButtonField({ id: "f-006-rsvp", color: "#ffffff" }),
    ],
  },
];

// ---------------------------------------------------------------------------
// Sample Invites
// ---------------------------------------------------------------------------

export const mockInvites: Invite[] = [
  {
    id: "inv-001",
    templateId: "tpl-001",
    templateSlug: "birthday-pastel",
    userId: "usr-dulmaa-01",
    title: "Анужин 6 нас",
    shareSlug: "anujin-6-nas-2026",
    status: "published",
    isPublic: true,
    values: {
      event_title:  { text: "Анужин 6 нас" },
      host_name:    { text: "Дулмаагийн Анужин" },
      event_date:   { text: "2026-07-20" },
      event_time:   { text: "14:00" },
      location:     { text: "Улаанбаатар хот, Сүхбаатар дүүрэг, 3-р хороо" },
      note:         { text: "Ирэхдээ бэлэг авчрахаа мартуузай! Хүүхэд бүр тавтай морилно." },
    },
    eventDate: "2026-07-20T14:00:00.000Z",
    eventTime: "14:00",
    eventLocation: "Улаанбаатар хот",
    eventLocationUrl: "https://maps.google.com/?q=Ulaanbaatar",
    rsvpCount: 12,
    viewCount: 84,
    createdAt: "2026-06-01T08:00:00.000Z",
    updatedAt: "2026-06-05T10:30:00.000Z",
  },
  {
    id: "inv-002",
    templateId: "tpl-002",
    templateSlug: "wedding-classic",
    userId: "usr-bat-01",
    title: "Бат-Эрдэнэ & Солонго нарын хурим",
    shareSlug: "bat-erdene-solongo-hurim-2026",
    status: "published",
    isPublic: false,
    values: {
      couple_names: { text: "Бат-Эрдэнэ & Солонго" },
      event_title:  { text: "Хуримын ёслолд урьж байна" },
      host_name:    { text: "Батын гэр бүл болон Солонгын гэр бүлийн зүгээс" },
      event_date:   { text: "2026-08-15" },
      event_time:   { text: "12:00" },
      location:     { text: "Шангри-Ла зочид буудал, Улаанбаатар" },
    },
    eventDate: "2026-08-15T12:00:00.000Z",
    eventTime: "12:00",
    eventLocation: "Шангри-Ла зочид буудал",
    eventLocationUrl: "https://maps.google.com/?q=Shangri-La+Ulaanbaatar",
    rsvpCount: 48,
    viewCount: 320,
    createdAt: "2026-05-20T09:00:00.000Z",
    updatedAt: "2026-06-10T14:00:00.000Z",
  },
  {
    id: "inv-003",
    templateId: "tpl-005",
    templateSlug: "graduation-modern",
    userId: "usr-tsengel-01",
    title: "Гантулгын Цэнгэлийн төгсөлтийн ёслол",
    shareSlug: "tsengel-graduation-2026",
    status: "published",
    isPublic: true,
    values: {
      event_title:  { text: "Төгсөлтийн ёслол 2026" },
      degree:       { text: "Програм хангамж инженерч — МУИС" },
      host_name:    { text: "Гантулгын Цэнгэл" },
      event_date:   { text: "2026-07-05" },
      event_time:   { text: "10:00" },
      location:     { text: "МУИС-ийн их танхим, Сүхбаатар дүүрэг" },
    },
    eventDate: "2026-07-05T10:00:00.000Z",
    eventTime: "10:00",
    eventLocation: "МУИС-ийн их танхим, Сүхбаатар дүүрэг",
    rsvpCount: 27,
    viewCount: 156,
    createdAt: "2026-06-02T07:30:00.000Z",
    updatedAt: "2026-06-08T11:00:00.000Z",
  },
  {
    id: "inv-004",
    templateId: "tpl-006",
    templateSlug: "corporate-elegant",
    userId: "usr-munkh-01",
    title: "Монгол Телеком — Жилийн тайлант хурал 2026",
    shareSlug: "mongol-telecom-annual-2026",
    status: "draft",
    isPublic: false,
    values: {
      event_title:    { text: "Жилийн тайлант хурал 2026" },
      organization:   { text: "Монгол Телеком ХК" },
      host_name:      { text: "Гүйцэтгэх захирал: Д. Мөнхбаяр" },
      event_date:     { text: "2026-09-10" },
      event_time:     { text: "09:00" },
      location:       { text: "Кемпински зочид буудал, Хан-Уул дүүрэг" },
      dress_code:     { text: "Ёслолын хувцас" },
    },
    eventDate: "2026-09-10T09:00:00.000Z",
    eventTime: "09:00",
    eventLocation: "Кемпински зочид буудал, Хан-Уул дүүрэг",
    rsvpCount: 0,
    viewCount: 3,
    createdAt: "2026-06-10T15:00:00.000Z",
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
];

// ---------------------------------------------------------------------------
// Sample RSVPs
// ---------------------------------------------------------------------------

export const mockRSVPs: RSVPEntry[] = [
  {
    id: "rsvp-001",
    inviteId: "inv-001",
    guestId: "guest-001",
    name: "Батцэцэг",
    status: "attending",
    partySize: 2,
    note: "Маш их баяртай байна! Утас: 9911-2233",
    createdAt: "2026-06-06T09:15:00.000Z",
  },
  {
    id: "rsvp-002",
    inviteId: "inv-001",
    name: "Мөнхзул",
    status: "attending",
    partySize: 3,
    createdAt: "2026-06-07T11:00:00.000Z",
  },
  {
    id: "rsvp-003",
    inviteId: "inv-001",
    name: "Оюунтуяа",
    status: "maybe",
    partySize: 1,
    note: "Цаг тохироод мэдэгдэнэ",
    createdAt: "2026-06-08T14:30:00.000Z",
  },
  {
    id: "rsvp-004",
    inviteId: "inv-002",
    guestId: "guest-002",
    name: "Энхжаргал",
    status: "attending",
    partySize: 2,
    note: "Тансаг ёслолд оролцохдоо баяртай байна",
    createdAt: "2026-06-09T10:00:00.000Z",
  },
];
